name: Build and Push Docker Image to DockerHub

on:
  release:
    types: [published]

env:
  DOCKER_IMAGE: dumbbin/dumbbin
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ variables.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tags
        id: docker_meta
        run: |
          TAGS="${{ env.DOCKER_IMAGE }}:latest ${{ env.DOCKER_IMAGE }}:${{ github.event.release.tag_name }}"
          echo "DOCKER_TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and Push Multi-Platform Image
        run: |
          docker buildx create --use
          docker buildx build --platform ${{ env.PLATFORMS }} \
            --tag ${{ env.DOCKER_IMAGE }}:latest \
            --tag ${{ env.DOCKER_IMAGE }}:${{ github.event.release.tag_name }} \
            --push .
